name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - v3.1.0

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: apt install
        run: |
          sudo apt update -y
          sudo apt install -y $(cat pkglist.txt)
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt
     

      - name: set LANG
        run: sh lang-zh.sh	  

      - name: Git Config
        run: git config user.name whitewum && git config user.email min.wu@vesoft.com

      - name: mike list delete
        run: |
          mike list
      - name: Mike Deploy 3.1.0
        run: |
          #mike delete v3.1.0 -p
          mike deploy 3.1.0 -p --rebase
          # mike set-default 3.1.0 -p --rebase
          mike list
      - name: show git branch
        run: | 
          git branch
          git checkout gh-pages
      - name: Compress
        run: |
          tar -vczf nebula-docs.tar.gz 3.1.0 versions.json *.html
          
      - name: Transfer
        # uses: garygrossgarten/github-action-scp@release
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: nebula-docs.tar.gz
          target: /usr/web

      - name: UnCompress
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /usr/web/nebula-docs/
            tar -xzf /usr/web/nebula-docs.tar.gz -C /usr/web/nebula-docs/
            mkdir -p /usr/web/nebula-docs/site/pdf/
            cp -f /usr/web/nebula-docs/3.1.0/pdf/NebulaGraph-CN.pdf /usr/web/nebula-docs/site/pdf/NebulaGraph-book.pdf
            
#            pip3 install --upgrade pip
#            pip3 install -r /usr/web/nebula-docs/requirement.txt
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.DEPLOY_TOKEN }}
      #     publish_dir: ./site
